# Meta Audience Network references Facebook's Infer static-analysis
# annotations at compile time only — safe to ignore, they're never used
# at runtime. Generated by R8 into missing_rules.txt on the first release
# build after adding Meta Audience Network mediation.
-dontwarn com.facebook.infer.annotation.Nullsafe$Mode
-dontwarn com.facebook.infer.annotation.Nullsafe
